name: rice_mill_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.7

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"
# name: flutter_osc

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  lottie: ^1.0.1
  flutter_svg: ^0.19.0
  flutter_rating_bar: ^3.0.1+1
  dot_navigation_bar: ^0.2.0
  fluttertoast: ^8.0.3
  english_words: ^4.0.0
  flutter_search_bar: ^2.1.0
  map: ^0.3.0
  lipsum: ^1.0.1
  page_transition: ^2.0.1-nullsafety.0
  http: ^0.12.1
  flinq: ^1.1.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

# To add assets to your application, add an assets section, like this:
assets:
    - assets/Lottie.json
    - assets/splashscreen2.json
    - assets/welcome1.json
    - assets/background.json
    - assets/welcome2.json
    - assets/welcome3.json
    - assets/bubble-animated-background.svg
    - assets/wc1.jpg
    - assets/waterwave1.jpg
    - assets/waterwave2.png
    - assets/waterwave3.png
    - assets/waterwave7.jpg
    - assets/flame.png
    - assets/rice6.png
    - assets/rice7.jpg
    - assets/r1.jpg
    - assets/rice.jpg
    - assets/wc2.jpg
    - assets/wc1.png
    - assets/rice3.jpg
    - assets/rice2.jpg
    - assets/rice1.png
    - assets/riceitem1.jpg
    - assets/riceitem2.jpg
    - assets/riceitem3.jpg
    - assets/riceitem4.jpg
    - assets/icons/rice-bowl.png
    - assets/icons/rice1.svg
    - assets/icons/rice2.svg
    - assets/icons/rice3.svg
    - assets/icons/rice5.svg
    - assets/ricemill.jpg
    - assets/ricemill2.jpg
    - assets/ricemill3.jpg
    - assets/ricemill4.jpg
    - assets/marker_a.png
    - assets/marker_b.png
    - assets/ricebag1.png
    - assets/ricebag2.png
    - assets/ricebag.png
    - assets/ricebag3.jpg
    - assets/icons/tick.svg
    - assets/icons/search.svg
    - assets/icons/cart.svg
    - assets/icons/tag.svg
    - assets/icons/delivery.svg
    - assets/icons/card.svg
    - assets/icons/back.svg
    - assets/icons/search.svg
    - assets/icons/controls.svg
    - assets/icons/sort.svg
    - assets/icons/list.svg
    - assets/icons/chest.svg
    - assets/icons/bathtub.svg
    - assets/icons/desk.svg
    - assets/images/splash1.png
    - assets/images/furniture/furniture1.png
    - assets/images/splash2.png
    - assets/images/furniture/jacalyn-beales-435629-unsplash.png
    - assets/images/furniture/sven-brandsma-1379481-unsplash.png
    - assets/images/furniture/pexels-eric-montanah-1350789.jpg
    - assets/images/furniture/pexels-patryk-kamenczak-775219.jpg
    - assets/images/furniture/pexels-pixabay-276534.jpg
    - assets/images/furniture/pexels-steve-johnson-923192.jpg
    - assets/images/furniture/items/dacey.png
    - assets/images/furniture/items/elly.png
    - assets/images/furniture/items/table 2.png
    - assets/images/furniture/items/ezgif.com-crop.png
    - assets/images/furniture/items/CHair 2.png
    - assets/images/furniture/items/chair3.png
flutter_intl:
    enabled: true

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
